# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Özgür Adem Işıklı
tagline:             Software Developer
url:                 http://ozguradem.net
baseurl:             ""

# About/contact
author:
  name:              Özgür Adem Işıklı
  url:               https://twitter.com/iozguradem
  email:             i.ozguradem@gmail.com
  twitter_username:  iozguradem

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

plugins_dir: [
  jekyll-sitemap
]
paginate_path: "page:num"