# Site settings
title: Özgür Adem Işıklı
email: i.ozguradem@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tecrübe sahibi olduğum konular: PHP, JS, Laravel, Node.js, 
  Sails.js, Meteor.js, PHPUnit, Selenium, PHPSpec, Codeception,
  Git, Laravel, Symfony2, Memcached, Redis, Linux Sistemlerler,
  MySQL, MSSQL, Oracle vb.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.ozguradem.net/" # the base hostname & protocol for your site
twitter_username: iozguradem
github_username:  ozziest

# Build settings
markdown: kramdown
paginate: 10

authors:
  ozziest:
    display_name: Özgür Adem Işıklı
    bio: Full Stack Developer
    avatar: https://pbs.twimg.com/profile_images/466225886530789377/P-fkjNMZ.jpeg
    email: i.ozguradem@gmail.com
    web: http://ozziest.github.io
    twitter: iozguradem
    github: ozziest
    facebook: TheMornie
    linkedin: http://tr.linkedin.com/in/ozguradem/
