title: Özgür Adem Işıklı
description: This is the personal website and the blog of Özgür Adem Işıklı.
keywords: özgür adem ışıklı, software development, blog
author: Özgür Adem Işıklı
footer: acnestis - 2023
